/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorial1.vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tutorial1.entidades.Categoria;
import tutorial1.entidades.Producto;
import tutorial1.modelo.CategoriaData;
import tutorial1.modelo.ProductoData;

/**
 *
 * @author Javier
 */
public class Tablas1 extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private ProductoData pd;
    private Producto productoElegido;

    /**
     * Creates new form Tablas1
     */
    public Tablas1() {
        initComponents();
        
        pd=new ProductoData();
        
        modelo=new DefaultTableModel();
        llenarCombos();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbCategorias = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jtfPrecio = new javax.swing.JTextField();
        jbActualizar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jsStock = new javax.swing.JSpinner();
        jcbCategoriaProducto = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestión de Productos");

        jcbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriasActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria");

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProductos);

        jLabel3.setText("Código");

        jLabel4.setText("Descripción");

        jLabel5.setText("Precio");

        jLabel6.setText("Categoría");

        jtfCodigo.setEnabled(false);
        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });

        jtfDescripcion.setEnabled(false);
        jtfDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescripcionFocusLost(evt);
            }
        });

        jtfPrecio.setEnabled(false);
        jtfPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPrecioFocusLost(evt);
            }
        });

        jbActualizar.setText("Actualizar");
        jbActualizar.setEnabled(false);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.setEnabled(false);
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jLabel7.setText("Stock");

        jsStock.setEnabled(false);

        jcbCategoriaProducto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbGuardar)
                .addGap(18, 18, 18)
                .addComponent(jbActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBorrar)
                .addGap(14, 14, 14)
                .addComponent(jbSalir)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(jtfDescripcion)
                                .addComponent(jtfPrecio))
                            .addComponent(jsStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNuevo)
                        .addGap(161, 161, 161)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jsStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbActualizar)
                            .addComponent(jbBorrar)
                            .addComponent(jbSalir)
                            .addComponent(jbGuardar)
                            .addComponent(jbNuevo)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        jbGuardar.setEnabled(true);
        limpiarCampos();
        activaCampos();
       jbActualizar.setEnabled(false);
        jbBorrar.setEnabled(false);
       
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jcbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriasActionPerformed
        // TODO add your handling code here:
        
        llenarTabla();
    }//GEN-LAST:event_jcbCategoriasActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        
        Producto pn=new Producto();
        pn.setCodigo(Integer.parseInt(jtfCodigo.getText()));
        pn.setDescripcion(jtfDescripcion.getText());
        pn.setPrecio(Double.parseDouble(jtfPrecio.getText()));
        pn.setCategoria((Categoria)jcbCategoriaProducto.getSelectedItem());
        pn.setStock((Integer)jsStock.getValue());
        
        pd.guardarProducto(pn);
        limpiarCampos();
        
         desactivaCampos();
       jbGuardar.setEnabled(false);
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosMouseClicked
        // TODO add your handling code here:
        jbActualizar.setEnabled(true);
        jbBorrar.setEnabled(true);
        int filaElegida=jtProductos.getSelectedRow();
        
        if(filaElegida!=-1){
                int idProducto=(Integer)jtProductos.getValueAt(filaElegida, 0);
                int codigo=(Integer)jtProductos.getValueAt(filaElegida, 1);
                String descripcion=(String)jtProductos.getValueAt(filaElegida, 2);
                double precio=(Double)jtProductos.getValueAt(filaElegida,3);
                Categoria catTabla=(Categoria)jtProductos.getValueAt(filaElegida, 4);
                int stock=(Integer)jtProductos.getValueAt(filaElegida, 5);
                
                jtfCodigo.setText(codigo+"");
                jtfDescripcion.setText(descripcion);
                jtfPrecio.setText(precio+"");
                jcbCategoriaProducto.setSelectedItem(catTabla);
                jsStock.setValue(stock);
                
                activaCampos();
                productoElegido=new Producto();
                productoElegido.setIdProducto(idProducto);
                productoElegido.setCodigo(codigo);
                productoElegido.setDescripcion(descripcion);
                productoElegido.setPrecio(precio);
                productoElegido.setCategoria(catTabla);
                productoElegido.setStock(stock);
        }
    }//GEN-LAST:event_jtProductosMouseClicked

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
        String val="[0-9]*";
        if(!jtfCodigo.getText().matches(val)){
        
            JOptionPane.showMessageDialog(this, "Debe ingresar sólo números");
            jtfCodigo.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoFocusLost

    private void jtfDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescripcionFocusLost
        // TODO add your handling code here:
        
        if(jtfDescripcion.getText().length()==0){
        
            JOptionPane.showMessageDialog(this, "La descripción no debe estar vacía");
            jtfDescripcion.requestFocus();
            
        }
    }//GEN-LAST:event_jtfDescripcionFocusLost

    private void jtfPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPrecioFocusLost
        // TODO add your handling code here:
        try{
                Double.parseDouble(jtfPrecio.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Precio no válido");
            jtfPrecio.requestFocus();
        }
        
    }//GEN-LAST:event_jtfPrecioFocusLost

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        
      
                int codigo=Integer.parseInt(jtfCodigo.getText());
                String descripcion=jtfDescripcion.getText();
                double precio=Double.parseDouble(jtfPrecio.getText());
                Categoria catNueva=(Categoria)jcbCategoriaProducto.getSelectedItem();
                int stock=(Integer)jsStock.getValue();
                
                
                productoElegido.setCodigo(codigo);
                productoElegido.setDescripcion(descripcion);
                productoElegido.setPrecio(precio);
                productoElegido.setStock(stock);
                productoElegido.setCategoria(catNueva);
                
                 pd.modificarProducto(productoElegido);
                 productoElegido=null;
                limpiarCampos();
                desactivaCampos();
                llenarTabla();
        jbActualizar.setEnabled(false);
        
        
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        pd.borraProducto(productoElegido);
        desactivaCampos();
        llenarTabla();
        jbBorrar.setEnabled(false);
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas1().setVisible(true);
            }
        });
    }
    
    private void llenarCombos(){
        CategoriaData cd=new CategoriaData();
        for(Categoria c:cd.obtenerCategorias()){
        
            jcbCategorias.addItem(c);
            jcbCategoriaProducto.addItem(c);
            
        }
    }
  
    private void armarCabecera(){
    
          ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Codigo");
        columnas.add("Descripcion");
        columnas.add("Precio");
        columnas.add("idCategoria");
        columnas.add("Stock");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        jtProductos.setModel(modelo);
    }
    
    private void llenarTabla(){
    
        borrarFilas();
        Categoria elegida=(Categoria)jcbCategorias.getSelectedItem();
     
        
        if(elegida!=null){
        
            for(Producto p:pd.obtenerProductos()){
            
                if(p.getCategoria().equals(elegida)){
                
                    modelo.addRow(new Object[]{p.getIdProducto(),p.getCodigo(),p.getDescripcion(),p.getPrecio(),p.getCategoria(),p.getStock()});
                }
            }
        }
    
    }
    
    private void limpiarCampos(){
    
        jtfCodigo.setText("");
        jtfDescripcion.setText("");
        jtfPrecio.setText("");
        jcbCategoriaProducto.setSelectedIndex(0);
        jsStock.setValue(0);
        
    }
    
    private void borrarFilas(){
    
        int a =modelo.getRowCount()-1;

                for(int i=a;i>=0;i--){
   
                    modelo.removeRow(i );
            }
    }
    
    private void activaCampos(){
        jtfCodigo.setEnabled(true);
        jtfDescripcion.setEnabled(true);
        jtfPrecio.setEnabled(true);
        jsStock.setEnabled(true);
       jcbCategoriaProducto.setEnabled(true);
       
    }
    private void desactivaCampos(){
         jtfCodigo.setEnabled(false);
        jtfDescripcion.setEnabled(false);
        jtfPrecio.setEnabled(false);
        jsStock.setEnabled(false);
       jcbCategoriaProducto.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Categoria> jcbCategoriaProducto;
    private javax.swing.JComboBox<Categoria> jcbCategorias;
    private javax.swing.JSpinner jsStock;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables
}
